# Generated by Django 5.2.8 on 2025-11-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("creatures", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="creature",
            name="student_name",
            field=models.CharField(default=None, max_length=250),
        ),
    ]
