# Generated by Django 5.2.8 on 2025-11-19 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("creatures", "0001_initial"),
        ("excuses", "0001_initial"),
        ("inventions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("medium", "Medium"),
                            ("hard", "Hard"),
                        ],
                        default="easy",
                        max_length=20,
                    ),
                ),
                ("xp_reward", models.PositiveIntegerField(default=10)),
                ("is_active", models.BooleanField(default=True)),
                ("times_assigned", models.PositiveIntegerField(default=0)),
                ("times_completed", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "main_enemy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions_with_creature",
                        to="creatures.creature",
                    ),
                ),
                (
                    "recommended_excuse",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions_with_excuse",
                        to="excuses.excuse",
                    ),
                ),
                (
                    "required_invention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="missions_with_invention",
                        to="inventions.invention",
                    ),
                ),
            ],
        ),
    ]
